### ISSUE TITLE
Can I use this library to do an export in pgc format?

### ISSUE THREAD

**Issue by tonsV2** [habx/pg-commands#22]

**Comment by clementlecorre** [comment]
Hi @tonsV2! I'm sorry for the late reply,

You can use the following formats:
https://github.com/habx/pg-commands/blob/f9d9a820ae3492743fb53bb57743c0dda9c0d31d/pg_dump.go#L25-L26
Note: You can configure them here, but I use by default the "custom" mode ⏫ 
```
  -F, --format=c|d|t|p         output file format (custom, directory, tar,
                               plain text (default))
```

**Comment by tonsV2** [comment]
Thanks for getting back to me. Eventually I ended up implementing a Bash based solution.
