### ISSUE TITLE
Expose Method For Specifying Filename

### ISSUE THREAD

**Issue by bbernays** [habx/pg-commands#23]
I attempted to dump a few small tables. The actions occurred completed so fast that the timestamp used to ensure uniqueness were all the same. It would be great to expose a method that enables a user to specify the full filename

**Comment by clementlecorre** [comment]
Hi @bbernays!

I have created an enhancement to support a specific name for the output file of a Postgres dump.

It's ok for you? 😄 
https://github.com/habx/pg-commands/pull/24/files
