### ISSUE TITLE
No error returned by dump.Exec() if pg_dump binary not found

### ISSUE THREAD

**Issue by stephenpmurray** [habx/pg-commands#27]
As in the title. 

Running the following code, based on the example:
```
func backupPostGres(host, user, pass, db, backupDir string, port int) error {
	filename := "backup.tar"
	dump := pg.NewDump(&pg.Postgres{
		Host:     host,
		Port:     port,
		DB:       db,
		Username: user,
		Password: pass,
	})
	dump.SetPath(backupDir)
	dump.SetFileName(filename)
	res := dump.Exec(pg.ExecOptions{StreamPrint: false})
	if res.Error != nil {
		return res.Error.Err
	}
	fmt.Println(res.Output)
	return nil
}
```
Yielded no errors and no log output. 

When the binary _is_ present and returns an error, the above code  simply returns the error message `exit status 1`. It would be worth including wrapping the error with `Error.CmdOutput` and logging this in the example. e.g:

```
	if res.Error != nil {
		err := fmt.Errorf("%w: %s", res.Error.Err, res.Error.CmdOutput)
		log.Print(err)
		return err
	}
```

**Comment by clementlecorre** [comment]
I have add check before dump/restore: https://github.com/habx/pg-commands/pull/33
