### ISSUE TITLE
No output despite setting StreamPrint to true

### ISSUE THREAD

**Issue by tonsV2** [habx/pg-commands#32]
As the title indicates, I get no output despite creating my object as below.

    dumpExec := dump.Exec(pg.ExecOptions{StreamPrint: true})

I'm using version v0.3.0.

Please let me know if I should post the rest of my code or if there's anything else I can do to assist.

**Comment by clementlecorre** [comment]
Hello @tonsV2 !
I want the rest of the code for better diagnosis.
You can also try the full command to test it from the terminal.

```
fmt.Println("Pg dump command:  " + dumpExec.FullCommand)
```

_If the command does not return any result then there will be no output with the print stream option_
