### ISSUE TITLE
Stream logs to other destinations than stdout

### ISSUE THREAD

**Issue by tonsV2** [habx/pg-commands#41]
As part of a system I'm working on we're dumping (and restoring) some fairly large databases (+50GB). Obviously that takes some time and we would like to keep the users aware of the progress.

The problem I'm encountering is that the output destination is hard coded to stdout as seen [here](https://github.com/habx/pg-commands/blob/04039bde31ffdfd281e87c430cdf8a1f0d4387fd/utils.go#L22).

Please let me know if there's a better way of solving the above issue. But I think this would be best solved by adding a io.Writer to the [ExecOptions](https://github.com/habx/pg-commands/blob/04039bde31ffdfd281e87c430cdf8a1f0d4387fd/utils.go#L10) struct. It should obviously default to os.Stdout but it could be used to stream the output to multiple destinations ranging from a simple file to a database while the dump is taking place.

Would you guys be interested in a PR implementing the above feature?

**Comment by clementlecorre** [comment]
@tonsV2 Yes I am interested for your PR. No problem to add this feature to the library 👍

**Comment by tonsV2** [comment]
@clementlecorre Great! I'll send you a PR in a not too distant future

**Comment by clementlecorre** [comment]
released here : https://github.com/habx/pg-commands/releases/tag/v0.6.0
