### ISSUE TITLE
pg_dump: illegal option -- blob Error

### ISSUE THREAD

**Issue by keanesnow98** [habx/pg-commands#50]
Hi, I am using postgres v14
And I have downloaded github.com/habx/pg-commands v0.6.1 in my golang backend project.
I have set the correct env path to postgresql bin directory.
But if I run the backend, I got `pg_dump: illegal option -- blob` error when I attempt to dump.
Please, help!

**Comment by clementlecorre** [comment]
Hello @keanesnow98 ! Can you give me an example of the code you use?
